// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ace-landing/BoldAdventure.tsx": () => import("../components/mockups/ace-landing/BoldAdventure.tsx"),
  "./components/mockups/ace-landing/ModernClean.tsx": () => import("../components/mockups/ace-landing/ModernClean.tsx"),
  "./components/mockups/ace-landing/NaturalEarthy.tsx": () => import("../components/mockups/ace-landing/NaturalEarthy.tsx")
};
